### ISSUE TITLE
Bug in 2.1.1 version

### ISSUE THREAD

**Issue by hashirshoaeb** [TabooSun/overlay_tutorial#33] opened 2022-01-11 07:28 UTC
Logs
``` 
: Error: The method 'OverlayTutorialHoleLayer.addToScene' has fewer positional arguments than those of overridden method 'ContainerLayer.addToScene'.
../…/widgets/overlay_tutorial_hole_layer.dart:16
  void addToScene(ui.SceneBuilder builder) {
       ^
: Context: This is the overridden method ('addToScene').
../…/rendering/layer.dart:1095
  void addToScene(ui.SceneBuilder builder, [ Offset layerOffset = Offset.zero ]) {
       ^

: Warning: Operand of null-aware operation '??' has type 'Color' which excludes null.
../…/lib/flutter_datetime_picker.dart:311
 - 'Color' is from 'dart:ui'.
                  color: theme.backgroundColor ?? Colors.white,
                               ^
2

FAILURE: Build failed with an exception.

* Where:
Script 'C:\Users\hashi\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 1005

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDevDebug'.
> Process 'command 'C:\Users\hashi\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
```

Tested on android device.

Flutter doctor:
```
[✓] Flutter (Channel stable, 2.5.3, on Microsoft Windows [Version 10.0.22000.376], locale en-PK)
    • Flutter version 2.5.3 at C:\Users\hashi\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (3 months ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\hashi\AppData\Local\Android\sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.63.2)
    • VS Code at C:\Users\hashi\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.32.0

[✓] Connected device (3 available)
    • sdk gphone x86 (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)

• No issues found!
```

**Comment by TabooSun** [comment] 2022-01-11 07:42
This is due to https://github.com/TabooSun/overlay_tutorial/issues/30...

You can try either to:
1. Upgrade your Flutter to 2.8.0 and above
2. Downgrade `overlay_tutorial` to `2.1.0`

Not a bug. Closing...

If you disagree, please reopen this issue.

**Closed as completed by TabooSun** 2022-01-11 07:42 UTC
